---
- name: Deploy Jenkins CI
  hosts: jenkins_server
  remote_user: vagrant
  become: yes

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.jenkins
    - geerlingguy.git
    - tecris.maven
    - geerlingguy.ansible

- name: Deploy Nexus Server
  hosts: nexus_server
  remote_user: vagrant
  become: yes

  roles:
    - geerlingguy.java
    - savoirfairelinux.nexus3-oss

- name: Deploy Sonar Server
  hosts: sonar_server
  remote_user: vagrant
  become: yes

  roles:
    - wtanaka.unzip
    - geerlingguy.sonar

- name: On Premises Windows Server
  hosts: app_server
  remote_user: vagrant
  become: yes

  roles:
    - jenkins-keys-config